# Generated by Django 4.2.15 on 2024-08-26 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='additional_info',
            field=models.JSONField(default=None),
        ),
    ]
