# Generated by Django 4.2.15 on 2024-08-28 12:07

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident_manager', '0005_alter_incident_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incident',
            old_name='status',
            new_name='validation_status',
        ),
        migrations.AddField(
            model_name='district',
            name='center',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='division',
            name='center',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='incident',
            name='task_status',
            field=models.CharField(choices=[('open', 'OPEN'), ('closed', 'CLOSED'), ('postponed', 'POSTPONED')], default='open', max_length=50),
        ),
        migrations.AddField(
            model_name='thana',
            name='center',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
