# Generated by Django 4.2.15 on 2024-08-31 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer_hub', '0002_volunteer_thana'),
        ('incident_manager', '0006_rename_status_incident_validation_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='district',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='incident_manager.district'),
        ),
        migrations.AddField(
            model_name='incident',
            name='volunteer',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='volunteer_hub.volunteer'),
        ),
    ]
