# Generated by Django 4.2.15 on 2024-08-27 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident_manager', '0004_district_division_thana_district_division_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='status',
            field=models.CharField(choices=[('pending', 'PENDING'), ('validated', 'VALIDATED'), ('rejected', 'REJECTED')], default='pending', max_length=50),
        ),
    ]
