# Generated by Django 4.2.15 on 2024-08-30 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident_manager', '0006_rename_status_incident_validation_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='image',
            field=models.ImageField(null=True, upload_to='Incident/'),
        ),
    ]
