# Generated by Django 4.2.15 on 2024-08-30 18:45

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incident_manager', '0007_incident_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, default=None, geography=True, null=True, srid=4326),
        ),
    ]
